### ISSUE TITLE
Investigate Pinch Valve Possibilities

### ISSUE THREAD

**Issue by MadsR** [Aarhus-University-MPE/BioDiscover#65]
### Description of the new feature / enhancement

Investigate the possibility of replacing the current design (linear actuator) valve for the phase 2 system with an alternative Pinch Valve design.

### Scenario when this would be used?

This implementation aims to improve the flushing success rate.

### Supporting information

Commercial products might be too large to implement, so custom made designs could be necessary.
The current design is already fully custom, so price should not be affected significantly.

**Mechanism Principle**
https://youtu.be/IPQDjLitMTY

**Comment by Fogh-Mec-Ing** [comment]
A pinch valve have successfully been added to a system and seems to show promising results.
The next generation of the system will implement this feature, and thereby further prove the reliability.
